

```{r}
summary(Copy_of_Research_Project_Responses_Form_Responses_1)
```
```{r}
ggplot(data = Copy_of_Research_Project_Responses_Form_Responses_1) +
  geom_bar(mapping = aes(x = cgpa)) +
  labs (x = "GPA Lower-Bound", y ="Count") +
  theme_economist()
```

```{r}
ggplot(data = Copy_of_Research_Project_Responses_Form_Responses_1) +
  geom_bar(mapping = aes(x = hlg)) +
  labs (x = "How likely are you to attend graduate school two to three years after graduation?", y ="Count") +
  theme_economist()
```

```{r}
ggplot(data = Copy_of_Research_Project_Responses_Form_Responses_1) +
  geom_bar(mapping = aes(x = hlgi)) +
  labs (x = "How likely are you to attend graduate school immediately after graduation?", y ="Count") +
  theme_economist()
```



```{r}
ggplot(data = Copy_of_Research_Project_Responses_Form_Responses_1) +
  geom_bar(mapping = aes(x = cgpa)) +
  labs (x = "GPA Lower-Bound", y ="Count") +
  theme_economist()
```


```{r}
sd(Copy_of_Research_Project_Responses_Form_Responses_1$hlgi)
sd(Copy_of_Research_Project_Responses_Form_Responses_1$cgpa)
sd(X2_3ofgradschool$hlg2)
```
```{r}
var(Copy_of_Research_Project_Responses_Form_Responses_1$hlgi)
var(Copy_of_Research_Project_Responses_Form_Responses_1$cgpa)
var(X2_3ofgradschool$hlg2)
```

```{r}
group_by(Copy_of_Research_Project_Responses_Form_Responses_1) %>%
  summarise(
    count = n(),
    mean = mean(hlg, na.rm = TRUE),
    sd = sd(hlg, na.rm = TRUE)
  )

```


```{r}
# Compute the analysis of variance
hlg.aov <- aov(cgpa ~ gs, data = Copy_of_Research_Project_Responses_Form_Responses_1)
# Summary of the analysis
summary(hlg.aov)
```

```{r}
(filter(Copy_of_Research_Project_Responses_Form_Responses_1, cgpa == 3.5 | cgpa == 3.75))


```

```{r}
table(Copy_of_Research_Project_Responses_Form_Responses_1$gs)
```

```{r}
subset(Copy_of_Research_Project_Responses_Form_Responses_1, cgpa > 3.5, select = c(gs))
subset(Copy_of_Research_Project_Responses_Form_Responses_1, Day == 1, select = -Temp)
subset(Copy_of_Research_Project_Responses_Form_Responses_1, select = Ozone:Wind)

with(airquality, subset(Ozone, Temp > 80))
```

